from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from tubefin.downloads import DownloadManager
from tubefin.library import OfflineLibrary
from tubefin.models import DownloadRecord, DownloadStatus, MediaItem


class DownloadManagerTests(unittest.TestCase):
    @patch("tubefin.downloads.threading.Thread")
    def test_enqueue_preserves_source_channel_and_thumbnail_metadata(
        self, thread: object
    ) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manager = DownloadManager(OfflineLibrary(Path(directory)))
            manager.executable = "yt-dlp"
            item = MediaItem(
                "video",
                "Video",
                subtitle="Creator",
                source="youtube",
                thumbnail_url="https://example/thumbnail.jpg",
                payload={
                    "webpage_url": "https://youtube.example/watch/video",
                    "channel_id": "creator-id",
                    "channel_url": "https://youtube.example/@creator",
                },
            )

            record = manager.enqueue(item)

            metadata = record.item.payload["download_metadata"]
            self.assertEqual(metadata["source"], "youtube")
            self.assertEqual(metadata["channel"], "Creator")
            self.assertEqual(metadata["original_thumbnail_url"], item.thumbnail_url)
            thread.return_value.start.assert_called_once()  # type: ignore[attr-defined]

    @patch("subprocess.Popen")
    def test_download_uses_browser_cookies_and_produces_offline_record(self, popen: object) -> None:
        with tempfile.TemporaryDirectory() as directory:
            library = OfflineLibrary(Path(directory))
            manager = DownloadManager(library, browser="firefox")
            manager.executable = "yt-dlp"
            target = library.download_directory / "download"
            target.mkdir(parents=True)
            (target / "video.mp4").write_bytes(b"media")
            record = DownloadRecord(
                "download",
                MediaItem(
                    "video",
                    "Video",
                    source="youtube",
                    payload={"webpage_url": "https://www.youtube.com/watch?v=video"},
                ),
                str(target),
                status=DownloadStatus.QUEUED,
            )
            library.upsert(record)
            popen.return_value = SimpleNamespace(  # type: ignore[attr-defined]
                stdout=iter([]),
                wait=lambda: 0,
            )

            manager._download(record.id, captions=False)

            command = popen.call_args.args[0]  # type: ignore[attr-defined]
            loaded = library.get(record.id)
            self.assertEqual(command[:3], ["yt-dlp", "--cookies-from-browser", "firefox"])
            self.assertIn("--merge-output-format", command)
            self.assertEqual(loaded.status, DownloadStatus.COMPLETE)  # type: ignore[union-attr]
            self.assertTrue(loaded.media_path.endswith("video.mp4"))  # type: ignore[union-attr]
            sidecar = json.loads((target / "video.tubefin.json").read_text())
            self.assertEqual(sidecar["source"], "youtube")
            self.assertEqual(sidecar["source_url"], "https://www.youtube.com/watch?v=video")
            self.assertIn("thumbnail_url", sidecar)

    @patch("subprocess.Popen")
    def test_download_requests_authored_subtitles_without_autogenerated_tracks(
        self, popen: object
    ) -> None:
        with tempfile.TemporaryDirectory() as directory:
            library = OfflineLibrary(Path(directory))
            manager = DownloadManager(library)
            manager.executable = "yt-dlp"
            target = library.download_directory / "download"
            target.mkdir(parents=True)
            (target / "video.mp4").write_bytes(b"media")
            (target / "video.webp").write_bytes(b"thumbnail")
            record = DownloadRecord(
                "download",
                MediaItem("video", "Video", source="youtube"),
                str(target),
            )
            library.upsert(record)
            popen.return_value = SimpleNamespace(stdout=iter([]), wait=lambda: 0)  # type: ignore[attr-defined]

            manager._download(record.id, captions=True)

            command = popen.call_args.args[0]  # type: ignore[attr-defined]
            loaded = library.get(record.id)
            self.assertIn("--all-subs", command)
            self.assertNotIn("--write-auto-subs", command)
            self.assertTrue(loaded.item.thumbnail_url.startswith("file://"))  # type: ignore[union-attr]

    @patch("subprocess.Popen")
    def test_minimum_quality_uses_a_valid_worst_stream_selector(self, popen: object) -> None:
        with tempfile.TemporaryDirectory() as directory:
            library = OfflineLibrary(Path(directory))
            manager = DownloadManager(library)
            manager.executable = "yt-dlp"
            target = library.download_directory / "download"
            target.mkdir(parents=True)
            (target / "video.mp4").write_bytes(b"media")
            record = DownloadRecord(
                "download",
                MediaItem("video", "Video", source="youtube"),
                str(target),
                quality="worst",
            )
            library.upsert(record)
            popen.return_value = SimpleNamespace(stdout=iter([]), wait=lambda: 0)  # type: ignore[attr-defined]

            manager._download(record.id, captions=False)

            command = popen.call_args.args[0]  # type: ignore[attr-defined]
            self.assertIn("worstvideo+worstaudio/worst", command)


if __name__ == "__main__":
    unittest.main()
